### ISSUE TITLE
Please publish latest version

### ISSUE THREAD

**Issue by roest01** [c0dr/node-football-data#6]
with `^0.1.2` i do not get the latest version out of npm from this repo.

current workaround: 
```
 npm install https://github.com/c0dr/node-football-data/tarball/master
```

**Comment by c0dr** [comment]
Thanks, I was able to replicate it and it indeed looks a bit strange.
In the process of fixing it.

**Comment by c0dr** [comment]
Just fixed it. npm doesn't allow unpublish anymore, so I had to publish a new version to fix this.

Thanks a lot for reporting this and enjoy the world cup ⚽️ .
Package has been a bit at the back of my head, might publish a better version in the next few days.

**Comment by roest01** [comment]
wow, thank's for this quick fix. Tested with `^0.1.3` and proved latest version. Start using this package now. Will do a PR if necessary :)
